### ISSUE TITLE
carriage returns and empty lines are removed from the end of files

### ISSUE THREAD

**Issue by dansteen** [VirtusLab/render#27]
Hi!  Thanks for your guys work on this. I was super-happy to find it.  One thing I did notice is that trailing carriage returns and blank lines in a file are removed in the output template.   This creates issues with some applications that require them.

Thanks!
Dan

**Comment by pawelprazak** [comment]
Could you provide a test case or an example?

**Comment by zipizap** [comment]
This issue is still present - see small demo in asciinema, showing that the last-empty-lines, and also the last-non-empty-line-EndOfLine\n are deleted in the output
A hacky-workaround seems to be to add some spaces (or probably a comment) in the last line, to prevent them being deleted 

Files also attached (as .txt)


https://asciinema.org/a/411355


[mytemplate.yaml.txt](https://github.com/VirtusLab/render/files/6412428/mytemplate.yaml.txt)
[mytemplate_with_spaces.yaml.txt](https://github.com/VirtusLab/render/files/6412429/mytemplate_with_spaces.yaml.txt)
[myvalues.yaml.txt](https://github.com/VirtusLab/render/files/6412430/myvalues.yaml.txt)

**Comment by zipizap** [comment]
Can also be tested with these 2 one-liners:

```
echo -e "line1\nline2: {{.some_thing}}\n\n\n\n" | ./render-linux-amd64 --silent --set some_thing=99

echo -e "line1\nline2: {{.some_thing}}\n\n\n\n#comment-to-avoid-deletion-of-last-lines" | ./render-linux-amd64 --silent --set some_thing=99

```


![image](https://user-images.githubusercontent.com/169160/116831480-f4d29500-abaf-11eb-8fe2-63542ee1cd1c.png)

**Comment by zipizap** [comment]
It seems it also happens that the last end-of-line-character (\n, newline) is deleted from lines in the middle of the template (and not just the last-lines).

In the following example, the original template contains a line with  '#' that is unexpectedly joined together with the next-line, effectively joining the 2 lines in just one... 

would it be possible to have a look at this issue? it seems more important than what it initially seemed... 
 

![Selection_015](https://user-images.githubusercontent.com/169160/116832624-ff902880-abb5-11eb-9aef-d7a2ed305b6d.png)

**Comment by dtelaroli** [comment]
The tool remove all comments and empty end lines.
I think that should have an option for disable this annoying feature.
